### ISSUE TITLE
CompoundNotFoundException: Cannot find compound for: L

### ISSUE THREAD

**Issue by heuermh** [biojava/biojava-adam#34]
```
 org.biojava.nbio.core.exceptions.CompoundNotFoundException: Cannot find compound for: L
    at org.biojava.nbio.core.sequence.storage.ArrayListSequenceReader.setContents(ArrayListSequenceReader.java:207)
    at org.biojava.nbio.core.sequence.template.AbstractSequence.<init>(AbstractSequence.java:93)
    at org.biojava.nbio.core.sequence.DNASequence.<init>(DNASequence.java:84)
    at org.biojava.nbio.core.sequence.io.DNASequenceCreator.getSequence(DNASequenceCreator.java:64)
    at org.biojava.nbio.core.sequence.io.GenbankReader.process(GenbankReader.java:165)
    at org.biojava.nbio.core.sequence.io.GenbankReader.process(GenbankReader.java:122)
    at org.biojava.nbio.adam.BiojavaAdamContext.readGenbankDna(BiojavaAdamContext.scala:472)
    at org.biojava.nbio.adam.BiojavaAdamContext.$anonfun$loadBiojavaGenbankDna$3(BiojavaAdamContext.scala:255)
    at org.biojava.nbio.adam.TryWith$.$anonfun$apply$1(TryWith.scala:37)
    at scala.util.Success.flatMap(Try.scala:251)
    at org.biojava.nbio.adam.TryWith$.apply(TryWith.scala:35)
    at org.biojava.nbio.adam.BiojavaAdamContext.loadBiojavaGenbankDna(BiojavaAdamContext.scala:254)
    at org.biojava.nbio.adam.BiojavaAdamContext.loadGenbankDna(BiojavaAdamContext.scala:242)
```

**Comment by heuermh** [comment]
https://github.com/biojava/biojava-adam/issues/34

**Comment by heuermh** [comment]
Closed as WontFix
